#pragma config(Sensor, dgtl1,  launchSolenoid, sensorDigitalOut)
#pragma config(Sensor, dgtl3,  pressureSwitch, sensorDigitalIn)
#pragma config(Motor,  port1,           compressor,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port4,           ballIn,        tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           latchServo,    tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port9,           rightMotor,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int servoMoving = 0;
int servoLockPosition = -20;
int disarmServoMoving = 0;
int pistonMoving = 0;
int threshold = 10;	//This is the variable you can alter to change the deadzone value of the joystick
int driveMode = 2; //Change this variable to change drive modes
//0 = tank mode with threshold
//1 = right stick = all arcade drive
//2 = left stick = all arcade drive
//3 = arcade right stick = forward/back, left stick = left/right KYLE STYLE
//4 = arcade right stick = left/right, left stick = forward/back  REVERSE KYLE STYLE

task main(){
motor[latchServo] = servoLockPosition;  //initialize latch servo to locked position
while(true){

	//This is the group of if statements to check if you pushed a button to change the drive mode
//	if(vexRT[Btn7U] ==1){
//		driveMode = 0;
//	} else if(vexRT[Btn7R] ==1){
//		driveMode = 1;
//	} else if(vexRT[Btn7D] == 1){
//		driveMode = 2;
//	}	else if(vexRT[Btn7L] == 1){
//		driveMode = 3;
//	} else if(vexRT[Btn8U] == 1){
//		driveMode = 4;
//	}

	//compressor
	if(SensorValue[pressureSwitch] == 0){ //if pressure switch cry that pressure too low
		motor[compressor] = 127;		//turn on pump to get some pressure
	}
	else{
		motor[compressor] = 0;  //if pressure switch is happy and full of pressure, then compressor can rest
	}
	//ball in
//	motor[ballIn] = vexRT[Ch3Xmtr2]; //uses left vertical joystick on partner controller to bring ball in
	motor[ballIn] = vexRT[Ch2];

	//retract and hold to test shooter
	if(vexRT[Btn7RXmtr2] ==1) {
		SensorValue[launchSolenoid] =1;}

	if(vexRT[Btn7UXmtr2] ==1) {
		SensorValue[launchSolenoid] =0;}


	//launch ball
	if(vexRT[Btn6UXmtr2] == 1) {        // If button 6U on partner (upper right shoulder button) is pressed:
    motor[latchServo] = 90;  // Turn the servo to unlatch the trunk latch "release the kraken".
    clearTimer(T1);
    servoMoving = 1;
  }


  if((servoMoving == 1)&&(time1[T1] >= 1000)){		//this means that if the ball has been shot and it has been over 1 second, then relatch and open solonoid.
  	servoMoving = 0;
  	motor[latchServo] = servoLockPosition; // Put servo back into place
  	SensorValue[launchSolenoid] = 1; //open solonoid to push cylinders to arm launcher
  	clearTimer(T3);
  	pistonMoving = 1;

  	}

  	if((pistonMoving == 1)&&(time1[T3] >= 1000)){
  		pistonMoving = 0;
  		SensorValue[launchSolenoid] = 0;
  	}
  	//disarm
  	if(vexRT[Btn7LXmtr2] == 1)         // If button 6U on partner (upper right shoulder button) is pressed:
  {
  	SensorValue[launchSolenoid] = 0;
    motor[latchServo] = 90;  // Turn the servo "release the kraken".
    clearTimer(T2);
    disarmServoMoving = 1;
  }
    if ((disarmServoMoving == 1) &&(time1[T2] >=1000)) {
    	disarmServoMoving =0;
    	motor[latchServo] =servoLockPosition;
  }



  //this launches ball with drive controller
  	//launch ball
	if(vexRT[Btn6U] == 1) {        // If button 6U on partner (upper right shoulder button) is pressed:
    motor[latchServo] = 90;  // Turn the servo to unlatch the trunk latch "release the kraken".
    clearTimer(T1);
    servoMoving = 1;
  }


  if((servoMoving == 1)&&(time1[T1] >= 1000)){		//this means that if the ball has been shot and it has been over 1 second, then relatch and open solonoid.
  	servoMoving = 0;
  	motor[latchServo] = servoLockPosition; // Put servo back into place
  	SensorValue[launchSolenoid] = 1; //open solonoid to push cylinders to arm launcher
  	clearTimer(T3);
  	pistonMoving = 1;

  	}

  	if((pistonMoving == 1)&&(time1[T3] >= 1000)){
  		pistonMoving = 0;
  		SensorValue[launchSolenoid] = 0;
  	}
  	//disarm
  	if(vexRT[Btn5U] == 1)         // If button 6U on partner (upper right shoulder button) is pressed:
  {
  	SensorValue[launchSolenoid] = 0;
    motor[latchServo] = 90;  // Turn the servo "release the kraken".
    clearTimer(T2);
    disarmServoMoving = 1;
  }
    if ((disarmServoMoving == 1) &&(time1[T2] >=1000)) {
    	disarmServoMoving =0;
    	motor[latchServo] =servoLockPosition;
  }





  switch (driveMode){	//This is the case statement for selecting the drive modes.
  	case 0:
  //Drive mode 0 Tank Mode
    if(abs(vexRT[Ch3]) > threshold)         // If the left joystick is greater than or less than the threshold:
    {
      motor[leftMotor]  = (vexRT[Ch3]);   // Left Joystick Y value.
    }
    else                                    // If the left joystick is within the threshold:
    {
      motor[leftMotor]  = 0;                // Stop the left motor (cancel noise)
    }

    if(abs(vexRT[Ch2]) > threshold)         // If the right joystick is greater than or less than the threshold:
    {
      motor[rightMotor] = -(vexRT[Ch2]);   // Right Joystick Y value.
    }
    else                                    // If the right joystick is within the threshold:
    {
      motor[rightMotor] = 0;                // Stop the right motor (cancel noise)
    }
  break;

  case 1:
	//Drive mode 1 right stick = all arcade drive
  	motor[leftMotor]  = (vexRT[Ch1] + vexRT[Ch2])/2;  // (y + x)/2
    motor[rightMotor] = (vexRT[Ch1] - vexRT[Ch2])/2;  // (y - x)/2
    break;

  case 2:
	//Drive mode 2 left stick = all arcade drive
  	motor[leftMotor]  = (vexRT[Ch4] + vexRT[Ch3])/2;  // (y + x)/2
    motor[rightMotor] = (vexRT[Ch4] - vexRT[Ch3])/2;  // (y - x)/2
  break;

  case 3:
	//Drive mode 3 arcade right stick = forward/back, left stick = left/right KYLE STYLE
  	motor[leftMotor]  = (vexRT[Ch4] + vexRT[Ch2])/2;  // (y + x)/2
    motor[rightMotor] = (vexRT[Ch4] - vexRT[Ch2])/2;  // (y - x)/2
    break;

    case 4:
  //Drive mode 4 arcade right stick = left/right, left stick = forward/back REVERSE KYLE STYLE
  	motor[leftMotor]  = (vexRT[Ch1] + vexRT[Ch3])/2;  // (y + x)/2
    motor[rightMotor] = (vexRT[Ch1] - vexRT[Ch3])/2;  // (y - x)/2
    break;
	}
}
}
