#pragma config(Motor,  port1,           left,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,           right,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

motor[left] = 63;
wait1Msec(5000);

}
